### ISSUE TITLE
Problem in `FV` with escaped quotes

### ISSUE THREAD

**Issue by bilow-factual** [spencertipping/ni#24]
This may not be part of the CSV spec (if one even exists), but this example fails:

[failing_line.txt](https://github.com/spencertipping/ni/files/2380917/failing_line.txt)

```
$ ni failing_line.txt FV | cat
ok1	ok2
$ ni failing_line.txt FC | cat
ok1	ok2	ok3	"\"bad4\""	ok5	ok6	ok7
```

**Comment by spencertipping** [comment]
Sadly CSV quoting uses the considerably more bogus `""` notation, womp womp: https://tools.ietf.org/html/rfc4180#page-2

I should probably add escape-char support though. I mean what are the odds that you've got JSON inside CSV or something? (Well actually...)

**Comment by bilow-factual** [comment]
hahaha

**Comment by spencertipping** [comment]
Have you reprimanded your CSV supplier? :)

I did push another change to `FV`: now it handles newlines correctly, turning them into `\r` inside the quoted output. Tabs become eight spaces. So `FV` should be a to-spec CSV->TSV translator with those exceptions. I haven't done backslash-quote conversion because it would break some legitimate CSVs (e.g. `"foo\","bar"`), but it wouldn't be hard to write a variant that parsed CSV that way.

For the meantime I'm gonna close this issue, then if we want more stuff we can add a new alternative.

**Comment by michaelbilow** [comment]
Sounds good.
